import requests
from time import sleep

url = 'http://132.231.14.168/HttpCommand'

script_name = "testScript2"
script = """smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()
smua.measure.i()"""

script_content = f"""loadscript {script_name}
{script}
endscript
"""

batch_size = 32

lines = script_content.split("\n")
batches = len(lines) // batch_size
remaining = len(lines) % batch_size

payloads = []

for i in range(batches):
    offset = i * batch_size

    content = ""
    for i in range(offset, offset + batch_size):
        content += lines[i] + "\n"
    payloads.append({"command": "shellInput", "value": content})

if remaining > 0:
    offset = batches * batch_size

    content = ""
    for i in range(offset, len(lines)):
        content += lines[i] + "\n"
    payloads.append({"command": "shellInput", "value": content})

payloads.append({"command": "shellInput",
                "value": f"{script_name}.save()"})

for payload in payloads:
    x = requests.post(url, json = payload)
    print(x.text)
    sleep(0.001)
