import requests
from time import sleep

url = 'http://132.231.14.168/HttpCommand'

payloads = [{"command": "shellInput", "value": """loadscript bufferedScriptC
b.clear()
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
"""},
{"command": "shellInput", "value": """smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
"""},
{"command": "shellInput", "value": """smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
"""},
{"command": "shellInput", "value": """smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)
smua.measure.v(b)

endscript
"""},
{"command": "shellInput", "value": "bufferedScriptC.save()"}]


for payload in payloads:
    x = requests.post(url, json = payload)
    print(x.text)
    sleep(0.001)
